### ISSUE TITLE
{ error: insert into "contracts" ("contract_desc", "contract_header", "owner_id", "signee_id") values ($1, $2, $3, $4) - duplicate key value violates unique constraint "contracts_pkey"

### ISSUE THREAD

**Issue by todddrinkwater** [todddrinkwater/signhere#26]
When using pgsql on Heroku, the app will not allow user to update contracts or create new ones. In addition to the error in the title, I also recieved:

2017-07-09T08:28:02.830148+00:00 app[web.1]: { error: insert into "contracts" ("contract_desc", "contract_header", "owner_id", "signee_id") values ($1, $2, $3, $4) - duplicate key value violates unique constraint "contracts_pkey"
2017-07-09T08:28:02.830163+00:00 app[web.1]:     at Connection.parseE (/app/node_modules/pg/lib/connection.js:567:11)
2017-07-09T08:28:02.830164+00:00 app[web.1]:     at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:391:17)
2017-07-09T08:28:02.830164+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:129:22)
2017-07-09T08:28:02.830165+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-07-09T08:28:02.830166+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2017-07-09T08:28:02.830166+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2017-07-09T08:28:02.830167+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:134:10)
2017-07-09T08:28:02.830167+00:00 app[web.1]:     at TCP.onread (net.js:548:20)
2017-07-09T08:28:02.830168+00:00 app[web.1]:   name: 'error',
2017-07-09T08:28:02.830169+00:00 app[web.1]:   length: 192,
2017-07-09T08:28:02.830169+00:00 app[web.1]:   severity: 'ERROR',
2017-07-09T08:28:02.830170+00:00 app[web.1]:   code: '23505',
2017-07-09T08:28:02.830170+00:00 app[web.1]:   detail: 'Key (id)=(2) already exists.',
2017-07-09T08:28:02.830170+00:00 app[web.1]:   hint: undefined,
2017-07-09T08:28:02.830171+00:00 app[web.1]:   position: undefined,
2017-07-09T08:28:02.830171+00:00 app[web.1]:   internalPosition: undefined,
2017-07-09T08:28:02.830171+00:00 app[web.1]:   internalQuery: undefined,
2017-07-09T08:28:02.830172+00:00 app[web.1]:   where: undefined,
2017-07-09T08:28:02.830172+00:00 app[web.1]:   schema: 'public',
2017-07-09T08:28:02.830172+00:00 app[web.1]:   table: 'contracts',
2017-07-09T08:28:02.830173+00:00 app[web.1]:   column: undefined,
2017-07-09T08:28:02.830173+00:00 app[web.1]:   dataType: undefined,
2017-07-09T08:28:02.830173+00:00 app[web.1]:   constraint: 'contracts_pkey',
2017-07-09T08:28:02.830174+00:00 app[web.1]:   file: 'nbtinsert.c',
2017-07-09T08:28:02.830174+00:00 app[web.1]:   line: '433',
2017-07-09T08:28:02.830174+00:00 app[web.1]:   routine: '_bt_check_unique' }

**Comment by todddrinkwater** [comment]
Solved by removing id keys from all seeds. Because id's were already automatically added via the increment primary key field of the database. This was causing double ups.
